/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.Macropax.BadguysChat.Client;

import com.Macropax.BadguysChat.Users;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JTextArea;

/**
 *
 * @author POPOOLA
 */
public class Settings extends javax.swing.JFrame {
SettingsC s;
List <Integer> BlockedId = new ArrayList <Integer>();
int Selection;
List<Users> FLi ;
MessageHandling MH;
JTextArea txtDisplay;
List<Integer>FriendsId = new ArrayList<Integer>();
    /**
     * Creates new form Settings
     */
    public Settings(SettingsC s ,List <Users> FL,MessageHandling MH,JTextArea txtDisplay,List<Integer> FriendId) {
        initComponents();
        this.FriendsId = FriendId;
        setVisible (true);
        this.txtDisplay = txtDisplay;
        this.MH = MH;
        FriendListModel FLM = new FriendListModel (false);
        FLM.AddValues(FL);
        FLi = FL;
        this.FL.setModel(FLM.ReturnModel());
        this.s =s;
        EN.setSelected(s.EN);
        EOM.setSelected(s.EOflineMessages);
        ES.setSelected(s.sound);
        
         try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        EOM = new javax.swing.JRadioButton();
        EN = new javax.swing.JRadioButton();
        ES = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        FL = new javax.swing.JList();
        jLabel1 = new javax.swing.JLabel();
        ClearLog = new javax.swing.JButton();
        LblckMessage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Settings");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        EOM.setText("Ennable Offline Messages");
        EOM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EOMActionPerformed(evt);
            }
        });

        EN.setText("Ennable Notifications");
        EN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ENActionPerformed(evt);
            }
        });

        ES.setText("Enable Sound");
        ES.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                ESStateChanged(evt);
            }
        });
        ES.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                ESPropertyChange(evt);
            }
        });
        ES.addVetoableChangeListener(new java.beans.VetoableChangeListener() {
            public void vetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {
                ESVetoableChange(evt);
            }
        });
        ES.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ESActionPerformed(evt);
            }
        });

        FL.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        FL.setSelectionBackground(new java.awt.Color(255, 0, 0));
        FL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FLMouseClicked(evt);
            }
        });
        FL.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                FLValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(FL);

        jLabel1.setText("Click to Block Friends");

        ClearLog.setText("Clear Log");
        ClearLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearLogActionPerformed(evt);
            }
        });

        LblckMessage.setForeground(new java.awt.Color(204, 0, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(212, 212, 212)
                .addComponent(jLabel1)
                .addContainerGap(143, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ES)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(EOM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(EN, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(ClearLog))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 100, Short.MAX_VALUE))
                    .addComponent(LblckMessage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(EOM)
                        .addGap(18, 18, 18)
                        .addComponent(EN)
                        .addGap(18, 18, 18)
                        .addComponent(ES)
                        .addGap(26, 26, 26)
                        .addComponent(ClearLog))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LblckMessage, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FLValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_FLValueChanged
        // TODO add your handling code here:
       
    }//GEN-LAST:event_FLValueChanged

    private void ClearLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearLogActionPerformed
        // TODO add your handling code here:
        txtDisplay.setText("");
        MH.ClearHistory();
    }//GEN-LAST:event_ClearLogActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_formWindowClosing

    private void ESStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_ESStateChanged
        // TODO add your handling code here:
                
    }//GEN-LAST:event_ESStateChanged

    private void ESPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_ESPropertyChange
    
        // TODO add your handling code here:
        
    }//GEN-LAST:event_ESPropertyChange

    private void ESVetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {//GEN-FIRST:event_ESVetoableChange
        // TODO add your handling code here:
        
    }//GEN-LAST:event_ESVetoableChange

    private void EOMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EOMActionPerformed
        // TODO add your handling code here:
        
        s.EOflineMessages = EOM.isSelected();
    }//GEN-LAST:event_EOMActionPerformed

    private void ENActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ENActionPerformed
        // TODO add your handling code here:
        s.EN=EN.isSelected();
        
    }//GEN-LAST:event_ENActionPerformed

    private void ESActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ESActionPerformed
        // TODO add your handling code here:
        s.sound = ES.isSelected();
    }//GEN-LAST:event_ESActionPerformed

    private void FLMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FLMouseClicked
        // TODO add your handling code here:
         int CurrentId;
        String Message;
        if (FL.getSelectedIndex()>=0)
        {
           CurrentId= FriendsId.get(FL.getSelectedIndex());
           if (BlockedId.contains(CurrentId))
           {
               for (int i =0 ;i <BlockedId.size();i++)
               {
                   if (BlockedId.get(i)== CurrentId)
                   {
                       BlockedId.remove(i);
                       break;
                   }
               }
               Message = "Removed from block list click again to block";
           }
           else {
               BlockedId.add(CurrentId);
               Message ="Blocked!! click again to unblock";
           }
           LblckMessage.setText(Message);
        }
        else
        {
            LblckMessage.setText("");
        }
    }//GEN-LAST:event_FLMouseClicked

    /**
     * @param args the command line arguments
     */
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ClearLog;
    private javax.swing.JRadioButton EN;
    private javax.swing.JRadioButton EOM;
    private javax.swing.JRadioButton ES;
    private javax.swing.JList FL;
    private javax.swing.JLabel LblckMessage;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
